"""Initial migration

Revision ID: d1646046343c
Revises: 
Create Date: 2026-06-08 11:20:05.269436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import geoalchemy2

# revision identifiers, used by Alembic.
revision: str = 'd1646046343c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Enable PostGIS extension
    op.execute('CREATE EXTENSION IF NOT EXISTS postgis;')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('capacity', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', 'maintenance', 'offline', name='busstatus'), server_default='inactive', nullable=False),
    sa.CheckConstraint('capacity >= 0', name='ck_buses_capacity_non_negative'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('label')
    )
    op.create_table('geocoding_caches',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('query', sa.String(), nullable=False),
    sa.Column('google_formatted_address', sa.String(), nullable=False),
    sa.Column('google_lat', sa.Float(), nullable=False),
    sa.Column('google_lng', sa.Float(), nullable=False),
    sa.Column('google_geocoded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('google_place_id', sa.String(), nullable=True),
    sa.CheckConstraint('google_lat >= -90 AND google_lat <= 90', name='ck_geocoding_caches_lat_range'),
    sa.CheckConstraint('google_lng >= -180 AND google_lng <= 180', name='ck_geocoding_caches_lng_range'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('query')
    )
    op.create_table('routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route_name', sa.String(), nullable=False),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='LINESTRING', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('schedule_template', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('route_name', name='uq_routes_route_name')
    )
    op.execute('CREATE INDEX IF NOT EXISTS idx_routes_geometry ON routes USING gist (geometry)')
    op.create_table('stops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stop_name', sa.String(), nullable=False),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('geofence_radius', sa.Float(), nullable=False),
    sa.Column('campus_zone', sa.String(), nullable=True),
    sa.CheckConstraint('geofence_radius > 0', name='ck_stops_geofence_radius_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute('CREATE INDEX IF NOT EXISTS idx_stops_location ON stops USING gist (location)')
    op.create_table('users',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('student', 'driver', 'admin', name='userrole'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('route_stops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('stop_id', sa.Integer(), nullable=False),
    sa.Column('stop_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
    sa.ForeignKeyConstraint(['stop_id'], ['stops.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('route_id', 'stop_id', name='uq_route_stops_route_stop'),
    sa.UniqueConstraint('route_id', 'stop_order', name='uq_route_stops_route_order')
    )
    op.create_table('trips',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('bus_id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Uuid(), nullable=True),
    sa.Column('trip_status', sa.Enum('scheduled', 'active', 'completed', 'cancelled', name='tripstatus'), nullable=False),
    sa.Column('scheduled_departure', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actual_departure', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_arrival', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_arrival', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('actual_arrival IS NULL OR actual_departure IS NULL OR actual_arrival >= actual_departure', name='ck_trips_actual_arrival_after_departure'),
    sa.CheckConstraint('scheduled_arrival IS NULL OR scheduled_arrival >= scheduled_departure', name='ck_trips_scheduled_arrival_after_departure'),
    sa.ForeignKeyConstraint(['bus_id'], ['buses.id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute('CREATE INDEX IF NOT EXISTS ix_trips_bus_status ON trips (bus_id, trip_status)')
    op.execute('CREATE INDEX IF NOT EXISTS ix_trips_route_scheduled_departure ON trips (route_id, scheduled_departure)')
    op.create_table('distance_matrix_logs',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('bus_id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Uuid(), nullable=True),
    sa.Column('origin_lat', sa.Float(), nullable=False),
    sa.Column('origin_lng', sa.Float(), nullable=False),
    sa.Column('destination_stop_id', sa.Integer(), nullable=False),
    sa.Column('destination_lat', sa.Float(), nullable=False),
    sa.Column('destination_lng', sa.Float(), nullable=False),
    sa.Column('google_requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('google_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('google_distance_m', sa.Float(), nullable=True),
    sa.Column('google_status', sa.String(), nullable=False),
    sa.Column('google_raw_response', sa.JSON(), nullable=True),
    sa.Column('actual_arrival', sa.DateTime(timezone=True), nullable=True),
    sa.Column('google_error_seconds', sa.Integer(), nullable=True),
    sa.CheckConstraint('google_distance_m IS NULL OR google_distance_m >= 0', name='ck_distance_matrix_logs_distance_non_negative'),
    sa.CheckConstraint('google_duration_seconds IS NULL OR google_duration_seconds >= 0', name='ck_distance_matrix_logs_duration_non_negative'),
    sa.ForeignKeyConstraint(['bus_id'], ['buses.id'], ),
    sa.ForeignKeyConstraint(['destination_stop_id'], ['stops.id'], ),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gps_locations',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('bus_id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Uuid(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('coordinates', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('speed', sa.Float(), nullable=True),
    sa.Column('heading', sa.Float(), nullable=True),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint('accuracy IS NULL OR accuracy >= 0', name='ck_gps_locations_accuracy_non_negative'),
    sa.CheckConstraint('heading IS NULL OR (heading >= 0 AND heading <= 360)', name='ck_gps_locations_heading_range'),
    sa.CheckConstraint('speed IS NULL OR speed >= 0', name='ck_gps_locations_speed_non_negative'),
    sa.ForeignKeyConstraint(['bus_id'], ['buses.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute('CREATE INDEX IF NOT EXISTS idx_gps_locations_coordinates ON gps_locations USING gist (coordinates)')
    op.execute('CREATE INDEX IF NOT EXISTS ix_gps_locations_bus_timestamp ON gps_locations (bus_id, timestamp)')
    op.execute('CREATE INDEX IF NOT EXISTS ix_gps_locations_trip_timestamp ON gps_locations (trip_id, timestamp)')
    op.create_table('stop_arrivals',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('trip_id', sa.Uuid(), nullable=False),
    sa.Column('stop_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dwell_time_seconds', sa.Integer(), nullable=True),
    sa.Column('google_predicted_eta_seconds', sa.Integer(), nullable=True),
    sa.CheckConstraint('dwell_time_seconds IS NULL OR dwell_time_seconds >= 0', name='ck_stop_arrivals_dwell_time_non_negative'),
    sa.CheckConstraint('google_predicted_eta_seconds IS NULL OR google_predicted_eta_seconds >= 0', name='ck_stop_arrivals_google_eta_non_negative'),
    sa.ForeignKeyConstraint(['stop_id'], ['stops.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trip_id', 'stop_id', name='uq_stop_arrivals_trip_stop')
    )
    op.create_table('prediction_comparisons',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('distance_matrix_log_id', sa.Uuid(), nullable=False),
    sa.Column('trip_id', sa.Uuid(), nullable=False),
    sa.Column('stop_id', sa.Integer(), nullable=False),
    sa.Column('bus_id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('bus_lat', sa.Float(), nullable=False),
    sa.Column('bus_lng', sa.Float(), nullable=False),
    sa.Column('bus_speed_kmh', sa.Float(), nullable=True),
    sa.Column('stops_remaining', sa.Integer(), nullable=True),
    sa.Column('google_eta_seconds', sa.Integer(), nullable=True),
    sa.Column('google_distance_m', sa.Float(), nullable=True),
    sa.Column('actual_arrival', sa.DateTime(timezone=True), nullable=True),
    sa.Column('google_error_seconds', sa.Integer(), nullable=True),
    sa.CheckConstraint('bus_lat >= -90 AND bus_lat <= 90', name='ck_prediction_comparisons_bus_lat_range'),
    sa.CheckConstraint('bus_lng >= -180 AND bus_lng <= 180', name='ck_prediction_comparisons_bus_lng_range'),
    sa.CheckConstraint('bus_speed_kmh IS NULL OR bus_speed_kmh >= 0', name='ck_prediction_comparisons_speed_non_negative'),
    sa.CheckConstraint('google_distance_m IS NULL OR google_distance_m >= 0', name='ck_prediction_comparisons_distance_non_negative'),
    sa.CheckConstraint('google_eta_seconds IS NULL OR google_eta_seconds >= 0', name='ck_prediction_comparisons_google_eta_non_negative'),
    sa.CheckConstraint('stops_remaining IS NULL OR stops_remaining >= 0', name='ck_prediction_comparisons_stops_remaining_non_negative'),
    sa.ForeignKeyConstraint(['bus_id'], ['buses.id'], ),
    sa.ForeignKeyConstraint(['distance_matrix_log_id'], ['distance_matrix_logs.id'], ),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
    sa.ForeignKeyConstraint(['stop_id'], ['stops.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prediction_comparisons')
    op.drop_table('stop_arrivals')
    op.drop_index('ix_gps_locations_trip_timestamp', table_name='gps_locations')
    op.drop_index('ix_gps_locations_bus_timestamp', table_name='gps_locations')
    op.drop_index('idx_gps_locations_coordinates', table_name='gps_locations', postgresql_using='gist')
    op.drop_table('gps_locations')
    op.drop_table('distance_matrix_logs')
    op.drop_index('ix_trips_route_scheduled_departure', table_name='trips')
    op.drop_index('ix_trips_bus_status', table_name='trips')
    op.drop_table('trips')
    op.drop_table('route_stops')
    op.drop_table('users')
    op.drop_index('idx_stops_location', table_name='stops', postgresql_using='gist')
    op.drop_table('stops')
    op.drop_index('idx_routes_geometry', table_name='routes', postgresql_using='gist')
    op.drop_table('routes')
    op.drop_table('geocoding_caches')
    op.drop_table('buses')
    # ### end Alembic commands ###
